version: "3.8"

services:
  postgres-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=to-do-list-nuven
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=post

  spring-app:
    image: yohansdocker0/todo-nuven:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/to-do-list-nuven
    depends_on:
      - postgres-db
